CREATE TABLE IF NOT EXISTS meter_alerts (
    ID INTEGER NOT NULL AUTOINCREMENT PRIMARY KEY,
    ORG_ID VARCHAR NOT NULL,
    DEVICE_ID  VARCHAR NOT NULL,
    ALERT_TYPE VARCHAR,
    START_TIME TIMESTAMP_TZ NOT NULL,
    END_TIME TIMESTAMP_TZ,
    SOURCE VARCHAR,
    UNIQUE (ORG_ID, DEVICE_ID, ALERT_TYPE, START_TIME, SOURCE)
);

-- Migration for existing tables:
ALTER TABLE meter_alerts ADD COLUMN IF NOT EXISTS SOURCE VARCHAR;